import '../store/types.dart';

/// Expanded food database with Sri Lankan foods, sides, curries & popular items.
/// Per-unit values for items with servingQty > 1.
class FoodDatabase {
  static const List<FoodItem> breakfastItems = [
    FoodItem(id: 'b1', name: 'Puttu', category: 'breakfast',
      description: 'Rice flour & coconut puttu', icon: '🍚',
      calories: 240, protein: 4, carbs: 42, fat: 8,
      servingSize: '1 cylinder', servingQty: 1, unit: 'cylinder'),
    FoodItem(id: 'b2', name: 'Thosai', category: 'breakfast',
      description: 'Rice & urad dal dosa', icon: '🥞',
      calories: 130, protein: 4, carbs: 20, fat: 3,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b3', name: 'Idly', category: 'breakfast',
      description: 'Steamed rice cakes', icon: '⚪',
      calories: 65, protein: 2, carbs: 12, fat: 0,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b4', name: 'String Hoppers', category: 'breakfast',
      description: 'Idiyappam', icon: '🍜',
      calories: 45, protein: 1, carbs: 8, fat: 1,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b5', name: 'Egg Roti', category: 'breakfast',
      description: 'Godamba roti with egg filling', icon: '🥚',
      calories: 350, protein: 14, carbs: 38, fat: 16,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b6', name: 'Oats Porridge', category: 'breakfast',
      description: 'Oats with milk and banana', icon: '🥣',
      calories: 310, protein: 12, carbs: 48, fat: 8,
      servingSize: '1 bowl', servingQty: 1, unit: 'bowl'),
    FoodItem(id: 'b7', name: 'Bread & Eggs', category: 'breakfast',
      description: '2 toast + 2 scrambled eggs', icon: '🍳',
      calories: 380, protein: 22, carbs: 35, fat: 14,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'b8', name: 'Pittu & Coconut Milk', category: 'breakfast',
      description: 'Pittu with lunu miris', icon: '🥥',
      calories: 210, protein: 3, carbs: 26, fat: 11,
      servingSize: '1 cylinder', servingQty: 1, unit: 'cylinder'),
    FoodItem(id: 'b9', name: 'Fruit Smoothie Bowl', category: 'breakfast',
      description: 'Mixed fruits, yogurt, granola', icon: '🍓',
      calories: 280, protein: 10, carbs: 45, fat: 6,
      servingSize: '1 bowl', servingQty: 1, unit: 'bowl'),
    FoodItem(id: 'b10', name: 'Protein Pancakes', category: 'breakfast',
      description: 'Oat pancakes with whey protein', icon: '🥞',
      calories: 340, protein: 28, carbs: 35, fat: 8,
      servingSize: '3 pancakes', servingQty: 3, unit: 'pc'),
    FoodItem(id: 'b11', name: 'Pol Roti', category: 'breakfast',
      description: 'Coconut flatbread', icon: '🫓',
      calories: 180, protein: 3, carbs: 22, fat: 9,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b12', name: 'Milk Rice (Kiribath)', category: 'breakfast',
      description: 'Rice cooked in coconut milk', icon: '🍚',
      calories: 220, protein: 4, carbs: 32, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b13', name: 'Hopper (Appa)', category: 'breakfast',
      description: 'Bowl-shaped rice flour pancake', icon: '🥣',
      calories: 110, protein: 2, carbs: 18, fat: 3,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b14', name: 'Egg Hopper', category: 'breakfast',
      description: 'Hopper with fried egg', icon: '🥚',
      calories: 180, protein: 7, carbs: 18, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b15', name: 'Uppuma', category: 'breakfast',
      description: 'Semolina savory porridge', icon: '🥣',
      calories: 190, protein: 5, carbs: 28, fat: 6,
      servingSize: '1 bowl', servingQty: 1, unit: 'bowl'),
    FoodItem(id: 'b16', name: 'Parotta', category: 'breakfast',
      description: 'Layered flaky flatbread', icon: '🫓',
      calories: 260, protein: 5, carbs: 36, fat: 10,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'b17', name: 'Roti (Plain)', category: 'breakfast',
      description: 'Wheat flour flatbread', icon: '🫓',
      calories: 120, protein: 3, carbs: 20, fat: 3,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
  ];

  static const List<FoodItem> lunchItems = [
    FoodItem(id: 'l1', name: 'White Rice', category: 'lunch',
      description: 'Steamed white rice', icon: '🍚',
      calories: 200, protein: 4, carbs: 44, fat: 0,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'l2', name: 'Red Rice', category: 'lunch',
      description: 'Traditional red rice', icon: '🍚',
      calories: 210, protein: 5, carbs: 42, fat: 2,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'l3', name: 'Basmati Rice', category: 'lunch',
      description: 'Long grain basmati', icon: '🍚',
      calories: 190, protein: 4, carbs: 40, fat: 1,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'l4', name: 'Kottu Roti', category: 'lunch',
      description: 'Chopped roti with vegetables & chicken', icon: '🥘',
      calories: 620, protein: 24, carbs: 55, fat: 30,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l5', name: 'Biriyani', category: 'lunch',
      description: 'Chicken biryani with raita', icon: '🍚',
      calories: 680, protein: 32, carbs: 72, fat: 26,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l6', name: 'Fried Rice', category: 'lunch',
      description: 'Egg fried rice with vegetables', icon: '🍳',
      calories: 520, protein: 16, carbs: 68, fat: 18,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l7', name: 'Noodles', category: 'lunch',
      description: 'Stir-fried noodles with chicken', icon: '🍝',
      calories: 480, protein: 20, carbs: 58, fat: 16,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l8', name: 'Grilled Chicken Salad', category: 'lunch',
      description: 'Chicken breast, greens, olive oil', icon: '🥗',
      calories: 380, protein: 38, carbs: 12, fat: 18,
      servingSize: '1 bowl', servingQty: 1, unit: 'bowl'),
    FoodItem(id: 'l9', name: 'Fish Curry & Rice', category: 'lunch',
      description: 'Fish curry with red rice', icon: '🐟',
      calories: 510, protein: 34, carbs: 58, fat: 12,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l10', name: 'Lamprais', category: 'lunch',
      description: 'Dutch-Burgher rice packet', icon: '🍱',
      calories: 750, protein: 28, carbs: 82, fat: 32,
      servingSize: '1 packet', servingQty: 1, unit: 'packet'),
    FoodItem(id: 'l11', name: 'Roti & Dhal Curry', category: 'lunch',
      description: 'Wheat roti with lentil curry', icon: '🫓',
      calories: 420, protein: 16, carbs: 56, fat: 12,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'l12', name: 'Chicken Wrap', category: 'lunch',
      description: 'Tortilla wrap with chicken & vegetables', icon: '🌯',
      calories: 440, protein: 30, carbs: 42, fat: 14,
      servingSize: '1 wrap', servingQty: 1, unit: 'wrap'),
    FoodItem(id: 'l13', name: 'Poori & Curry', category: 'lunch',
      description: 'Deep fried bread with potato curry', icon: '🫓',
      calories: 380, protein: 8, carbs: 42, fat: 20,
      servingSize: '3 pieces', servingQty: 3, unit: 'pc'),
    FoodItem(id: 'l14', name: 'Chapati', category: 'lunch',
      description: 'Whole wheat flatbread', icon: '🫓',
      calories: 100, protein: 3, carbs: 18, fat: 2,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'l15', name: 'String Hopper Biriyani', category: 'lunch',
      description: 'Layered idiyappam biryani', icon: '🍜',
      calories: 480, protein: 22, carbs: 58, fat: 16,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'l16', name: 'Pittu & Curry', category: 'lunch',
      description: 'Pittu with chicken curry', icon: '🍚',
      calories: 450, protein: 20, carbs: 52, fat: 16,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
  ];

  static const List<FoodItem> dinnerItems = [
    FoodItem(id: 'd1', name: 'Rice & Curry (Light)', category: 'dinner',
      description: '½ cup rice + dhal + vegetables', icon: '🍛',
      calories: 380, protein: 18, carbs: 48, fat: 10,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd2', name: 'Grilled Fish & Vegetables', category: 'dinner',
      description: 'Grilled fish with steamed veg', icon: '🐟',
      calories: 320, protein: 36, carbs: 14, fat: 12,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd3', name: 'Chicken Soup', category: 'dinner',
      description: 'Clear chicken soup with vegetables', icon: '🍲',
      calories: 250, protein: 24, carbs: 18, fat: 8,
      servingSize: '1 bowl', servingQty: 1, unit: 'bowl'),
    FoodItem(id: 'd4', name: 'Egg Kottu', category: 'dinner',
      description: 'Kottu with egg & vegetables', icon: '🥘',
      calories: 480, protein: 16, carbs: 52, fat: 22,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd5', name: 'Vegetable Stir Fry', category: 'dinner',
      description: 'Mixed veg with tofu in soy sauce', icon: '🥦',
      calories: 280, protein: 14, carbs: 22, fat: 14,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd6', name: 'Chicken Breast & Salad', category: 'dinner',
      description: 'Grilled chicken with garden salad', icon: '🥗',
      calories: 350, protein: 40, carbs: 10, fat: 14,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd7', name: 'Omelette & Toast', category: 'dinner',
      description: '3-egg omelette with wheat toast', icon: '🍳',
      calories: 400, protein: 26, carbs: 28, fat: 18,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'd8', name: 'String Hoppers & Curry', category: 'dinner',
      description: 'Idiyappam with chicken curry', icon: '🍜',
      calories: 420, protein: 22, carbs: 54, fat: 12,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'd9', name: 'BBQ Chicken', category: 'dinner',
      description: 'Grilled BBQ chicken drumsticks', icon: '🍗',
      calories: 380, protein: 34, carbs: 8, fat: 24,
      servingSize: '2 pieces', servingQty: 2, unit: 'pc'),
    FoodItem(id: 'd10', name: 'KFC Chicken', category: 'dinner',
      description: 'Fried chicken pieces (KFC style)', icon: '🍗',
      calories: 520, protein: 28, carbs: 22, fat: 36,
      servingSize: '2 pieces', servingQty: 2, unit: 'pc'),
    FoodItem(id: 'd11', name: 'Chicken Burger', category: 'dinner',
      description: 'Crispy chicken burger', icon: '🍔',
      calories: 550, protein: 26, carbs: 42, fat: 30,
      servingSize: '1 burger', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'd12', name: 'Pizza Slice', category: 'dinner',
      description: 'Cheese & chicken pizza', icon: '🍕',
      calories: 280, protein: 12, carbs: 32, fat: 12,
      servingSize: '1 slice', servingQty: 1, unit: 'slice'),
    FoodItem(id: 'd13', name: 'Submarine / Sub', category: 'dinner',
      description: 'Chicken sub sandwich', icon: '🥖',
      calories: 480, protein: 24, carbs: 52, fat: 18,
      servingSize: '1 sub', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'd14', name: 'Shawarma', category: 'dinner',
      description: 'Chicken shawarma wrap', icon: '🌯',
      calories: 520, protein: 28, carbs: 44, fat: 24,
      servingSize: '1 wrap', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'd15', name: 'Devilled Chicken', category: 'dinner',
      description: 'Spicy dry chicken with peppers', icon: '🌶️',
      calories: 340, protein: 30, carbs: 12, fat: 18,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'd16', name: 'Devilled Prawns', category: 'dinner',
      description: 'Spicy stir-fried prawns', icon: '🦐',
      calories: 280, protein: 26, carbs: 10, fat: 14,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'd17', name: 'Chinese Rolls', category: 'dinner',
      description: 'Deep fried chicken spring rolls', icon: '🥟',
      calories: 180, protein: 6, carbs: 18, fat: 10,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'd18', name: 'Cutlets', category: 'dinner',
      description: 'Deep fried fish/chicken cutlets', icon: '🍘',
      calories: 160, protein: 8, carbs: 14, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'd19', name: 'Pasta', category: 'dinner',
      description: 'Chicken pasta in cream sauce', icon: '🍝',
      calories: 520, protein: 22, carbs: 56, fat: 22,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
    FoodItem(id: 'd20', name: 'Rice & BBQ Combo', category: 'dinner',
      description: 'Rice with BBQ chicken & coleslaw', icon: '🍖',
      calories: 650, protein: 32, carbs: 68, fat: 24,
      servingSize: '1 plate', servingQty: 1, unit: 'plate'),
  ];

  static const List<FoodItem> snackItems = [
    FoodItem(id: 's1', name: 'Mixed Nuts', category: 'snack',
      description: 'Almonds, cashews, walnuts', icon: '🥜',
      calories: 180, protein: 6, carbs: 8, fat: 14,
      servingSize: '30g handful', servingQty: 1, unit: 'handful'),
    FoodItem(id: 's2', name: 'Banana', category: 'snack',
      description: '1 medium banana', icon: '🍌',
      calories: 105, protein: 1, carbs: 27, fat: 0,
      servingSize: '1 medium', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's3', name: 'Greek Yogurt', category: 'snack',
      description: 'Plain Greek yogurt 150g', icon: '🥛',
      calories: 140, protein: 15, carbs: 8, fat: 5,
      servingSize: '150g', servingQty: 1, unit: 'cup'),
    FoodItem(id: 's4', name: 'Protein Bar', category: 'snack',
      description: 'Whey protein bar', icon: '🍫',
      calories: 220, protein: 20, carbs: 24, fat: 8,
      servingSize: '1 bar', servingQty: 1, unit: 'bar'),
    FoodItem(id: 's5', name: 'Fruit Salad', category: 'snack',
      description: 'Mixed fresh fruits', icon: '🍎',
      calories: 120, protein: 2, carbs: 28, fat: 1,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 's6', name: 'Egg (Boiled)', category: 'snack',
      description: 'Hard boiled egg', icon: '🥚',
      calories: 70, protein: 6, carbs: 0, fat: 5,
      servingSize: '1 egg', servingQty: 1, unit: 'egg'),
    FoodItem(id: 's7', name: 'Peanut Butter Toast', category: 'snack',
      description: '1 toast with peanut butter', icon: '🍞',
      calories: 230, protein: 8, carbs: 22, fat: 12,
      servingSize: '1 slice', servingQty: 1, unit: 'slice'),
    FoodItem(id: 's8', name: 'Whey Protein Shake', category: 'snack',
      description: '1 scoop whey in water', icon: '🥤',
      calories: 130, protein: 25, carbs: 3, fat: 2,
      servingSize: '1 scoop', servingQty: 1, unit: 'scoop'),
    FoodItem(id: 's9', name: 'Wade (Vadai)', category: 'snack',
      description: 'Deep fried lentil vadai', icon: '🧆',
      calories: 130, protein: 5, carbs: 14, fat: 6,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's10', name: 'Biscuits & Tea', category: 'snack',
      description: 'Digestive biscuits + tea', icon: '🍪',
      calories: 60, protein: 1, carbs: 10, fat: 2,
      servingSize: '1 biscuit', servingQty: 1, unit: 'biscuit'),
    FoodItem(id: 's11', name: 'Isso Wade', category: 'snack',
      description: 'Prawn fritter', icon: '🦐',
      calories: 160, protein: 8, carbs: 14, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's12', name: 'Fish Bun', category: 'snack',
      description: 'Baked bun with fish filling', icon: '🐟',
      calories: 220, protein: 10, carbs: 28, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's13', name: 'Rolls (Chinese)', category: 'snack',
      description: 'Fried spring roll', icon: '🥟',
      calories: 180, protein: 6, carbs: 18, fat: 10,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's14', name: 'Patties', category: 'snack',
      description: 'Flaky pastry with curry filling', icon: '🥧',
      calories: 200, protein: 6, carbs: 20, fat: 10,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's15', name: 'Kavum', category: 'snack',
      description: 'Traditional oil cake', icon: '🍩',
      calories: 180, protein: 2, carbs: 26, fat: 8,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's16', name: 'Kokis', category: 'snack',
      description: 'Crispy traditional cookie', icon: '🍘',
      calories: 120, protein: 2, carbs: 14, fat: 6,
      servingSize: '2 pieces', servingQty: 2, unit: 'pc'),
    FoodItem(id: 's17', name: 'Aluwa', category: 'snack',
      description: 'Rice flour sweet', icon: '🍬',
      calories: 150, protein: 2, carbs: 28, fat: 4,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 's18', name: 'Milk Toffee', category: 'snack',
      description: 'Sri Lankan milk toffee', icon: '🍬',
      calories: 80, protein: 1, carbs: 14, fat: 2,
      servingSize: '2 pieces', servingQty: 2, unit: 'pc'),
  ];

  /// Side dishes & curries - can be added to any meal
  static const List<FoodItem> sideItems = [
    FoodItem(id: 'sd1', name: 'Dhal Curry', category: 'sides',
      description: 'Yellow lentil curry', icon: '🍛',
      calories: 120, protein: 8, carbs: 16, fat: 3,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd2', name: 'Chicken Curry', category: 'sides',
      description: 'Sri Lankan chicken curry', icon: '🍗',
      calories: 280, protein: 28, carbs: 8, fat: 14,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd3', name: 'Fish Curry', category: 'sides',
      description: 'Spicy fish curry with tamarind', icon: '🐟',
      calories: 220, protein: 26, carbs: 6, fat: 10,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd4', name: 'Egg Curry', category: 'sides',
      description: 'Boiled eggs in spicy gravy', icon: '🥚',
      calories: 190, protein: 14, carbs: 6, fat: 12,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd5', name: 'Pol Sambol', category: 'sides',
      description: 'Coconut sambol with chili & onion', icon: '🥥',
      calories: 90, protein: 2, carbs: 4, fat: 7,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd6', name: 'Lunu Miris', category: 'sides',
      description: 'Onion & chili relish', icon: '🌶️',
      calories: 35, protein: 1, carbs: 4, fat: 1,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd7', name: 'Seeni Sambol', category: 'sides',
      description: 'Caramelized onion sambol', icon: '🧅',
      calories: 110, protein: 2, carbs: 12, fat: 6,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd8', name: 'Kulambu (Kuzhambu)', category: 'sides',
      description: 'Tamarind based curry', icon: '🍲',
      calories: 150, protein: 6, carbs: 12, fat: 8,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd9', name: 'Fish Fry', category: 'sides',
      description: 'Deep fried spiced fish', icon: '🐟',
      calories: 180, protein: 18, carbs: 6, fat: 10,
      servingSize: '1 piece', servingQty: 1, unit: 'pc'),
    FoodItem(id: 'sd10', name: 'Chicken Fry', category: 'sides',
      description: 'Fried spiced chicken pieces', icon: '🍗',
      calories: 220, protein: 22, carbs: 8, fat: 12,
      servingSize: '2 pieces', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd11', name: 'Prawn Curry', category: 'sides',
      description: 'Spicy prawn curry', icon: '🦐',
      calories: 200, protein: 24, carbs: 4, fat: 10,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd12', name: 'Mutton Curry', category: 'sides',
      description: 'Slow-cooked mutton curry', icon: '🍖',
      calories: 320, protein: 26, carbs: 6, fat: 22,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd13', name: 'Beetroot Curry', category: 'sides',
      description: 'Mild beetroot coconut curry', icon: '🟣',
      calories: 80, protein: 2, carbs: 12, fat: 3,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd14', name: 'Pumpkin Curry', category: 'sides',
      description: 'Sweet pumpkin coconut curry', icon: '🟠',
      calories: 90, protein: 2, carbs: 14, fat: 3,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd15', name: 'Brinjal Moju', category: 'sides',
      description: 'Sweet & sour eggplant pickle', icon: '🍆',
      calories: 110, protein: 2, carbs: 10, fat: 7,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd16', name: 'Gotukola Sambol', category: 'sides',
      description: 'Pennywort salad', icon: '🥬',
      calories: 45, protein: 2, carbs: 6, fat: 1,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd17', name: 'Parippu (Dhal)', category: 'sides',
      description: 'Thick lentil dhal', icon: '🍛',
      calories: 140, protein: 9, carbs: 18, fat: 4,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd18', name: 'Rasam', category: 'sides',
      description: 'Tangy pepper soup', icon: '🍲',
      calories: 40, protein: 2, carbs: 6, fat: 1,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd19', name: 'Sambar', category: 'sides',
      description: 'Lentil & vegetable curry', icon: '🍲',
      calories: 130, protein: 7, carbs: 16, fat: 4,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd20', name: 'Potato Curry', category: 'sides',
      description: 'Spiced potato curry', icon: '🥔',
      calories: 140, protein: 3, carbs: 22, fat: 5,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd21', name: 'Cashew Curry', category: 'sides',
      description: 'Creamy cashew nut curry', icon: '🥜',
      calories: 240, protein: 6, carbs: 12, fat: 18,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd22', name: 'Jackfruit Curry', category: 'sides',
      description: 'Young jackfruit curry', icon: '🍈',
      calories: 110, protein: 3, carbs: 18, fat: 3,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd23', name: 'Coconut Chutney', category: 'sides',
      description: 'Ground coconut with green chili', icon: '🥥',
      calories: 60, protein: 1, carbs: 4, fat: 4,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd24', name: 'Achar (Pickle)', category: 'sides',
      description: 'Mixed vegetable pickle', icon: '🫙',
      calories: 50, protein: 1, carbs: 8, fat: 2,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd25', name: 'Cabbage Mallum', category: 'sides',
      description: 'Shredded cabbage with coconut', icon: '🥬',
      calories: 65, protein: 2, carbs: 6, fat: 4,
      servingSize: '1 serving', servingQty: 1, unit: 'serving'),
    FoodItem(id: 'sd26', name: 'Snake Gourd Curry', category: 'sides',
      description: 'Light snake gourd curry', icon: '🥒',
      calories: 70, protein: 3, carbs: 8, fat: 3,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd27', name: 'Crab Curry', category: 'sides',
      description: 'Spicy Sri Lankan crab curry', icon: '🦀',
      calories: 260, protein: 28, carbs: 6, fat: 14,
      servingSize: '1 cup', servingQty: 1, unit: 'cup'),
    FoodItem(id: 'sd28', name: 'Dry Fish Sambol', category: 'sides',
      description: 'Maldive fish flake sambol', icon: '🐟',
      calories: 130, protein: 16, carbs: 4, fat: 6,
      servingSize: '2 tbsp', servingQty: 1, unit: 'serving'),
  ];

  static List<FoodItem> getByCategory(String category) {
    switch (category) {
      case 'breakfast': return breakfastItems;
      case 'lunch': return lunchItems;
      case 'dinner': return dinnerItems;
      case 'snack': return snackItems;
      case 'sides': return sideItems;
      default: return [];
    }
  }

  /// Get main items + sides for a meal category
  static List<FoodItem> getWithSides(String category) {
    return [...getByCategory(category), ...sideItems];
  }

  static List<FoodItem> searchAll(String query) {
    final q = query.toLowerCase();
    return [
      ...breakfastItems,
      ...lunchItems,
      ...dinnerItems,
      ...snackItems,
      ...sideItems,
    ].where((item) =>
      item.name.toLowerCase().contains(q) ||
      item.description.toLowerCase().contains(q)
    ).toList();
  }
}
