// File generated by FlutterFire CLI.
// Firebase is temporarily disabled for Windows desktop builds.
// Re-enable firebase_core in pubspec.yaml and regenerate this file
// using `flutterfire configure` for Android/iOS builds.

// Stub class to prevent compile errors when Firebase packages are disabled.
class DefaultFirebaseOptions {
  // This will throw at runtime if called — Firebase must be re-enabled first.
  static dynamic get currentPlatform =>
    throw UnsupportedError('Firebase is not configured. Re-enable Firebase packages in pubspec.yaml.');
}
